FROM python:3-slim

WORKDIR /app

COPY /conf /conf

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install nginx \
    && apt-get -y install python3-pip python3-dev

RUN pip3 install -r /conf/requirements.txt

COPY /conf/nginx.conf /etc/nginx/nginx.conf

CMD service nginx start 

COPY . /app

RUN chmod +x /conf/start.sh

# Uncomment this if you're not using docker compose.
# CMD "/conf/start.sh"

